# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
#
# Copyright (C) 2019-2022 CERN.
# Copyright (C) 2019 Northwestern University.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

version: "2.2"
services:
  app:
    build:
      context: ./
      args:
        - ENVIRONMENT=DEV
    image: demo-inveniordm
    environment:
      - "INVENIO_ACCOUNTS_SESSION_REDIS_URL=redis://cache:6379/1"
      - "INVENIO_BROKER_URL=amqp://guest:guest@mq:5672/"
      - "INVENIO_CACHE_REDIS_URL=redis://cache:6379/0"
      - "INVENIO_CACHE_TYPE=redis"
      - "INVENIO_CELERY_BROKER_URL=amqp://guest:guest@mq:5672/"
      - "INVENIO_CELERY_RESULT_BACKEND=redis://cache:6379/2"
      - "INVENIO_SEARCH_HOSTS=['search:9200']"
      - "INVENIO_SECRET_KEY=CHANGE_ME"
      - "INVENIO_COMMUNITIES_IDENTITIES_CACHE_REDIS_URL=redis://cache:6379/4"
      - "INVENIO_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://demo-inveniordm:demo-inveniordm@db/demo-inveniordm"
      - "INVENIO_WSGI_PROXIES=2"
      - "INVENIO_RATELIMIT_STORAGE_URL=redis://cache:6379/3"
  frontend:
    build: ./docker/nginx/
    image: demo-inveniordm-frontend
    restart: "unless-stopped"
    ports:
      - "80"
      - "443"
  cache:
    image: registry.cern.ch/docker.io/library/redis:7
    restart: "unless-stopped"
    read_only: true
    ports:
      - "6379:6379"
  db:
    image: registry.cern.ch/docker.io/library/postgres:12.4
    restart: "unless-stopped"
    environment:
      - "POSTGRES_USER=demo-inveniordm"
      - "POSTGRES_PASSWORD=demo-inveniordm"
      - "POSTGRES_DB=demo-inveniordm"
    ports:
      - "5432:5432"
  pgadmin:
    image: registry.cern.ch/docker.io/dpage/pgadmin4:7.7
    restart: "unless-stopped"
    ports:
      - "5050:80"
      - "5051:443"
    environment:
      PGADMIN_DEFAULT_EMAIL: "info@inveniosoftware.org"
      PGADMIN_DEFAULT_PASSWORD: "demo-inveniordm"
    volumes:
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
  mq:
    image: registry.cern.ch/docker.io/library/rabbitmq:3-management
    restart: "unless-stopped"
    ports:
      - "15672:15672"
      - "5672:5672"
  search:
    image: registry.cern.ch/docker.io/opensearchproject/opensearch:2.15.0
    restart: "unless-stopped"
    environment:
      # settings only for development. DO NOT use in production!
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "discovery.type=single-node"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "localhost:9200/_cluster/health?wait_for_status=green",
        ]
      interval: 30s
      timeout: 30s
      retries: 5
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    ports:
      - "9200:9200"
      - "9600:9600"
  opensearch-dashboards:
    image: registry.cern.ch/docker.io/opensearchproject/opensearch-dashboards:2.15.0
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      # settings only for development. DO NOT use in production!
      - 'OPENSEARCH_HOSTS=["http://search:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
